### PR TITLE
CI/add fetch schedule

### PR DESCRIPTION
**Pull request by djacu**
Reinstate fetching schedule data during site build.

### CODE REVIEW

**Comment by sarcasticadmin** [comment]
Did the preview work??? I cant tell from the changes lol

**Comment by djacu** [comment]
> Did the preview work??? I cant tell from the changes lol

I forgot to include the fetch in both workflows. This next preview should be better. The word "plaintext" in my workshop is split into "plain text" with the updated schedule data.

It also works locally on my machine. :upside_down_face:

**Comment by djacu** [comment]
So I think the script is working. See the contents of the previous PR vs this one. The word "plaintext" is now two words. I didn't update the json file statically. It was fetched from sessionize's API.

PREVIOUS PR
https://github.com/nixcon/2024-na.nixcon.org/blob/gh-pages/pr-preview/pr-40/talks/index.html#L13

THIS PR
https://github.com/nixcon/2024-na.nixcon.org/blob/gh-pages/pr-preview/pr-41/talks/index.html#L13

**Comment by sarcasticadmin** [comment]
This looks to be the case in the preview thats served up too: 
ss-202402131707789743

**Review by sarcasticadmin — APPROVED** [review]
Ya automation! Nice work @djacu

**Comment by djacu** [comment]
> This looks to be the case in the preview thats served up too: ss-202402131707789743

I kept not seeing that because when I clicked on the schedule link it removes `pr-preview/pr-41` from the URL. I see it now!

**Review by davidnuon — APPROVED** [review]

**Pull request merged**
