### PR TITLE
content/add sponsor worldquant

### PR DESCRIPTION
**Pull request by djacu**
Add WorldQuant as a gold sponsor.

- [x] Fixed by replacing PNG with SVG. ~~Image proportions are messed up.  Probably because this is a png and all the other logos were svg.~~

### CODE REVIEW

**Review by sarcasticadmin — APPROVED** [review]
Preview looks good to me

Any thoughts on going with the logo that includes their name in the center? idk if we have access to a quality logo but I pulled this from the bottom of their homepage so you can see the difference: 
ss-202402221708627856

**Comment by djacu** [comment]
> Preview looks good to me
> 
> Any thoughts on going with the logo that includes their name in the center? idk if we have access to a quality logo but I pulled this from the bottom of their homepage so you can see the difference: ss-202402221708627856

I had initially tried that logo but it's a PNG and with the way we have the CSS setup, it ruined the proportions.
image

**Comment by sarcasticadmin** [comment]
I completely missed the second commit :laughing:

**Review by davidnuon — COMMENTED** [review]
lgtm, just need a :+1: from the powers that be and we can merge

**Comment by davidnuon** [comment]
image

**Review by davidnuon — APPROVED** [review]

**Pull request merged**
